### PR TITLE
Etcd provisioners

### PR DESCRIPTION
**Pull request by ffilippopoulos**

### CODE REVIEW

**Comment by george-angel** [comment]
Do you mind squashing all commits into one?

**Comment by ffilippopoulos** [comment]
Squashed!

**Comment by george-angel** [comment]
Also add one for cfssl? :)

**Comment by ffilippopoulos** [comment]
Added cfssl provisioner

**Review by george-angel — APPROVED** [review]

**Comment by george-angel** [comment]
Squash again before merging please

**Pull request merged**
